### PR TITLE
Issue 6 : Reload recommended jobs

### PR DESCRIPTION
**Pull request by Alex-Bakic**
# Reloading recommended jobs

#6

For a complete walkthrough on the development of the fixes in regards to this issue, the gist covering it all is just here -> https://gist.github.com/Alex-Bakic/58fad658206bd8db4ee183f983270f3b

### CODE REVIEW

**Comment by acron0** [comment]
@Alex-Bakic This is a great PR and I appreciated your write up. Thank you.

**Comment by acron0** [comment]
OK TO MERGE

**Comment by acron0** [comment]
OK TO MERGE

**Comment by WorksHubCodi** [comment]
Thanks for contributing! This code has been merged upstream!

**Pull request closed without merging**
