### PR TITLE
Job card hover transitions

### PR DESCRIPTION
**Pull request by eckardjf**
The job card hover transition for inverted buttons does not match the transition for buttons and borders (ease out is not triggered). This is because ease-in-out is specified on hover instead of the normal state.

### CODE REVIEW

**Comment by eckardjf** [comment]
I did not include `wh.css` since generating a new version with `lein sass once` seemed to produce many additional unrelated changes. Is it possible that it is not up to date?

**Comment by acron0** [comment]
@eckardjf Heya, thanks for the PR. The "unrelated changes" are usually due to a mismatch in versions of SASS:

``` bash
=> sassc -v                                                         
sassc: 3.4.8
libsass: 3.5.4
sass2scss: 1.1.1
sass: 3.5
```

But yeah, usually we do check in `wh.css`

**Comment by acron0** [comment]
@eckardjf Great spot on this issue. PR is very appreciated. My feedback is that whilst your solution works, I think it'd be more pertinent to keep the transition out of the button's "main" class (`.button--inverted` in `_buttons.sass`) and instead add it specifically for `.button--inverted` beneath `.card-border-color-#{$i - 1}` in `_cards.sass`, but above the hover section. This way the transition is kept specific to buttons on a card. What do you think?

**Comment by eckardjf** [comment]
My thinking was that making it global would mirror the global background transition on `.button` and cover cases where the two styles were used side by side elsewhere (or in the future) - but you're right, that is a bit broad for this particular case.

**Comment by acron0** [comment]
OK TO MERGE

**Comment by WorksHubCodi** [comment]
Thanks for contributing! This code has been merged upstream!

**Pull request closed without merging**
