### PR TITLE
Keyboard Dropdown

### PR DESCRIPTION
**Pull request by Alex-Bakic**
#30 

This PR covers most of the brief within the issue above, though there is one section : 

    highlighting a result in this way changes the text input to match the highlighted result

I found this to be tricky to implement , as once the input is set as the text it would change the recommendations to only that input value itself. So should it be set only in the re-frame db and allow the user to continue typing , or we say the only functionality associated with keydown would be pressing enter to submit the option ?

Also , aside from creating  a completely custom keyboard accessible dropdown, with ARIA labels and things , there is an [html element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) called `<datalist>` which might be an option. 

The pros:

- Simple, fully functional keyboard accessible dropdown
- screen-reader friendly
- fewer bugs, would only need to add event listeners 

The cons:

- not very flexible in terms of styling , though the defaults are alright
- messes with the border-radius of inputs , as it comes with a down-arrow selector, which , even when disabled , doesn't sit well with other wrapper elements. And even on disable it means standard date-picker elements also lose their down-arrow selector

### CODE REVIEW

**Comment by acron0** [comment]
Hi Alex, I am definitely open to suggestions on what you think is the best solution. It would be nice if it worked with all of our existing dropdowns otherwise potentially a lot of code to change. I think I also prefer the mechanism of pressing ENTER to confirm your selection rather than update as you move up and down

**Comment by Alex-Bakic** [comment]
Alrighty I've finished the dropdown , as I've kept it simpler with just the use of the ENTER to confirm. I've not used `<datalist>` or anything like that and so it fits in with all references of `input-suggestions` :+1:

**Comment by acron0** [comment]
@Alex-Bakic Can you remove `.nrepl-port` and add to `.gitignore`? Also you might want to bring this PR up to date, we don't include `wh.css` anymore

**Comment by Alex-Bakic** [comment]
Alrighty, all done . The branch is able to merge :+1:

**Pull request closed without merging**
